### ISSUE TITLE
[registry-operator]: scope of MVP 

### ISSUE THREAD

**Issue by malgorzatadutka** [registry-operator/adr#4]
### Context and Problem Statement

Minimum Viable Product (MVP) refers to the initial version of a product that includes only the essential features needed to meet the needs of early adopters and gather feedback for future development. 

MVP should be defined at the beginning of our project. If it comes to the `storage` implementation we can consider splitting work into main features:
- `filesystem`
- `azure`
- `gcs`
- `s3`

Moreover the `Registry` configuration file contains many parameters connected with logging, hooks, authorization, http server configuration. Please see: https://distribution.github.io/distribution/about/configuration/

### Considered Options

The MVP can contain the two protocols:
- `filesystem` - using CSI support
- `s3` (fields: `accesskey, secretkey, region, regionendpoint, bucket`) - using COSI support

It can implement configuring other fields such as:
- `storage.inmemory` - uses inmemory storage driver for tests purposes
- `storage.delete` - enables the deletion of image blobs and manifests by digest
- `storage.maintanance` - enables maintanance functions like uploadpurging and readonly.
- `auth.token` - configures authentication provider

Please remember that a well-defined scope enhances the efficiency of MVP development and the overall success of the product.

**Comment by malgorzatadutka** [comment]
Well, it is the simplest possible solution. In this case we don't need to communicate with CSI/COSI CRs, but on the other hand we won't test any specific scenarios connected with communication with driver's resources. I understand that the MVP will be fulfilled, because the `Registry` will be successfully configured, but we won't develop `Registry` CRD.

The plan: 
1) 0.1.0 - configuring `Registry` withdefault configuration
2) 0.2.0 - configuring with `s3`
3) 0.3.0 - configuring with `filesystem` ...

@purpleturtll @shanduur @majabojarska @niesmaczne

**Comment by shanduur** [comment]
LGTM. As a result of this ADR, could you please create a Roadmap (either as an issue or a `ROADMAP.md` file in [registry-operator/registry-operator](https://github.com/registry-operator/registry-operator)) and create milestones for `v0.1.0` and `v0.2.0`?
