### ISSUE TITLE
[registry-operator]: static site generator for documentation

### ISSUE THREAD

**Issue by shanduur** [registry-operator/adr#5]
### Context and Problem Statement

Effective documentation is paramount for the successful adoption and utilisation of the `registry-operator`, a robust tool tailored for managing CNCF Distribution Registry instances. As developers and DevOps teams engage with the `registry-operator`, they require comprehensive, easily accessible documentation to streamline deployment, scaling, and management tasks.

The choice of documentation framework or static site generator is crucial to ensure that the documentation meets the needs of our users. Templating flexibility, support for custom scripts, and availability of extra plugins for enhancing functionality are key factors to consider in this decision-making process.

### Considered Options

* [MKDocs](https://www.mkdocs.org) + [Material Theme for MKDocs](https://squidfunk.github.io/mkdocs-material/)
  * **Description**: MKDocs is a fast and simple static site generator specifically designed for project documentation. Material Theme for MKDocs offers a clean and responsive material design.
  * **Pros**: Easy to use and configure, extensive plugin ecosystem, Markdown-based content.
  * **Cons**: Limited theming options compared to other frameworks, less flexibility in customization.

* [Hugo](http://gohugo.io) + [Docsy Theme](https://www.docsy.dev)
  * **Description**: Hugo is a fast and flexible static site generator written in Go. Docsy Theme provides a modern, customizable theme tailored for technical documentation.
  * **Pros**: High performance, extensive theming and customization options, large community and ecosystem.
  * **Cons**: Steeper learning curve for beginners, may require more effort in initial setup and configuration.

* [Hugo](http://gohugo.io) + [Doks Theme](https://github.com/gethyas/doks)
  * **Description**: Doks is a Hugo theme optimized for technical documentation websites. It offers a clean and minimalist design with extensive customization options.
  * **Pros**: Tailored specifically for technical documentation, easy integration with Hugo's powerful templating system, active development.
  * **Cons**: Relatively new compared to other themes.

* [Docusaurus](https://docusaurus.io)
  * **Description**: Docusaurus is an open-source project for building, deploying, and maintaining open source project websites easily. It provides a focus on performance, offline support, and user engagement.
  * **Pros**: Designed for technical documentation and open source projects, built-in support for versioning, search, and localization.
  * **Cons**: Opinionated framework with less flexibility in customisation, may require additional effort for integration with existing toolchains.

* [Cobalt](http://cobalt-org.github.io)
  * **Description**: Cobalt is a static site generator written in Rust, designed for simplicity and performance. It focuses on providing a minimalistic yet powerful framework for building websites and blogs.
  * **Pros**: Minimalistic approach, Flexible templating.
  * **Cons**: Limited ecosystem, Learning curve.

* [Zola](https://www.getzola.org)
  * **Description**: Zola is a fast static site generator written in Rust. It prioritizes speed, simplicity, and extensibility, making it suitable for building anything from personal blogs to complex websites.
  * **Pros**: Speed, Feature-rich, Active community.
  * **Cons**: Limited theming options, Learning curve.

**Comment by shanduur** [comment]
## Bootstrapping 

1. *Docsy*
    ```sh
    hugo new site .
    git submodule add https://github.com/google/docsy.git themes/docsy
    (cd themes/docsy && git checkout v0.9.1)
    echo 'theme = "docsy"' >> hugo.toml
    ```

    This produces the following file structure:

    ```
    registry-operator.docsy
    ├── archetypes
    │   └── default.md
    ├── assets
    ├── content
    ├── data
    ├── hugo.toml
    ├── i18n
    ├── layouts
    ├── static
    └── themes
        └── docsy
           └── ...
    ```

2. *Docusaurus*
    ```sh
    npx create-docusaurus@latest registry-operator classic
    ```

    This produces the following file structure:

    ```
    registry-operator.mkdocs
    ├── docs
    │   └── index.md
    ├── mkdocs.yml
    └── venv
        └── ...
    ```

3. *Doks*
    ```sh
    npm create hyas@latest -- --template doks
    ```

    This produces the following file structure:
    
    ```
    registry-operator.doks
    ├── LICENSE
    ├── assets
    │   ├── cover.png
    │   ├── favicon.ico
    │   ├── favicon.png
    │   ├── favicon.svg
    │   ├── images
    │   ├── js
    │   │   └── custom.js
    │   ├── mask-icon.svg
    │   ├── scss
    │   │   └── common
    │   │       ├── _custom.scss
    │   │       └── _variables-custom.scss
    │   └── svgs
    ├── config
    │   ├── _default
    │   │   ├── hugo.toml
    │   │   ├── languages.toml
    │   │   ├── markup.toml
    │   │   ├── menus
    │   │   │   ├── menus.en.toml
    │   │   │   └── menus.nl.toml
    │   │   ├── module.toml
    │   │   └── params.toml
    │   ├── babel.config.js
    │   ├── next
    │   │   └── hugo.toml
    │   ├── postcss.config.js
    │   └── production
    │       └── hugo.toml
    ├── content
    │   ├── _index.md
    │   ├── blog
    │   │   ├── _index.md
    │   │   └── example
    │   │       └── index.md
    │   ├── docs
    │   │   ├── _index.md
    │   │   ├── guides
    │   │   │   ├── _index.md
    │   │   │   └── example.md
    │   │   └── reference
    │   │       ├── _index.md
    │   │       └── example.md
    │   └── privacy.md
    ├── layouts
    │   ├── index.html
    │   └── partials
    │       ├── footer
    │       │   └── script-footer-custom.html
    │       └── head
    │           ├── custom-head.html
    │           └── script-header.html
    ├── netlify.toml
    ├── package.json
    └── static
    ```

4. *Material for MKDocs*
    ```sh
    python3 -m venv venv && source ./venv/bin/activate
    pip install mkdocs-material
    mkdocs new .
    echo 'theme:' >> mkdocs.yml
    echo '  name: material' >> mkdocs.yml
    ```

    This produces the following file structure:

    ```
    registry-operator.mkdocs
    ├── docs
    │   └── index.md
    ├── mkdocs.yml
    └── venv
        └── ...
    ```

## Versioning

- _Docsy_: built-in support ([see docs](https://www.docsy.dev/docs/adding-content/versioning/));
- _Docusaurus_: built-in support ([see docs](https://docusaurus.io/docs/versioning));
- _Doks_: built-in support, but it is not particularly well documented ([see docs](https://getdoks.org/docs/recipes/versioning/));
- _Material for MKDocs_: supported via [Mike plugin](https://github.com/jimporter/mike).

**Comment by niesmaczne** [comment]
I’ve glanced over on those frameworks, and based on the resources available, Docsy seems like the best choice - the documentation is very useful, there is a big community around that. 

However I think there are some cons to all provided examples - almost all of them are plain, with large walls of text lacking visual differentiation. This causes the documents  to be hard to read and search. The biggest issue comes from color scheme of code blocks - they are blending too much with other parts of text. 

Another issue is lack of global vertical menu on the side, especially in the mobile version. Good option is to have two separate menus (at least in desktop version) - one for different pages, and other for sections on current page.

I think that with proper customization of Docsy, we would achieve easy to read and follow documentation, that will be useful for both neurotypical and neurodivergent users.
